export default [
    {
      id: '0',
      image: 'https://www.fariasribeiroimoveis.com.br/app/fotos/d7051d5f911aa91ff9f147eb6cea4f26.jpg',
      type: 'Apartmento',
      title: 'Park House Flamboyant',
      description: 'Lindo apartamento com 350M² em frente ao parque flamboyant, 5 minutos do Shopping Flamboyant',
      bed: 3,
      bedroom: 3,
      address: "R. 13, 205 - Jardim Goiás, Goiânia - GO",
      cep: "74810-170",
      oldPrice: "1.250.000,00",
      newPrice: "1.000.000,00",
      totalPrice: "1.000.000,00",
      coordinate: {
        latitude: -16.7041264,
        longitude: -49.2375369,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '1',
      image: 'https://2.bp.blogspot.com/-80Hem__bDeE/VR7GYsLLNLI/AAAAAAAAEfQ/dv0ljYtCHKw/s1600/the%2Bone.png',
      type: 'Apartamento',
      title: 'Lançamento - The One',
      description: 'O mais novo lançamento da EMAAR em frente ao parque flamboyant.',
      bed: 3,
      bedroom: 2,
      oldPrice: "1.150.000,00",
      newPrice: "930.000,00",
      totalPrice: "940.000,00",
      address: "R. 13, 145 - Jardim Goiás, Goiânia - GO",
      cep: "74810-170",
      coordinate: {
        latitude: -16.7032863,
        longitude: -49.2374933,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '2',
      image: 'https://2.bp.blogspot.com/-80Hem__bDeE/VR7GYsLLNLI/AAAAAAAAEfQ/dv0ljYtCHKw/s1600/the%2Bone.png',
      type: 'Apartamento',
      title: 'Test',
      description: 'O mais novo lançamento da EMAAR em frente ao parque flamboyant.',
      bed: 3,
      bedroom: 2,
      oldPrice: "1.150.000,00",
      newPrice: "990.000,00",
      totalPrice: "990.000,00",
      address: "R. 13, 145 - Jardim Goiás, Goiânia - GO",
      cep: "74810-170",
      coordinate: {
        latitude: -16.7047863,
        longitude: -49.2374933,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '3',
      image: 'https://lh5.googleusercontent.com/p/AF1QipNzYL21o0kfS2z607gMMwnHVTWamBzzSdvw9_Ui=w408-h725-k-no',
      type: 'Apartamento Duplex',
      title: 'Typical canarian house',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      bed: 4,
      bedroom: 3,
      oldPrice: "1.850.000,00",
      newPrice: "1.430.000,00",
      totalPrice: "1.450.000,00",
      address: "R. 46, 555 - Jardim Goiás, Goiânia - GO",
      cep: "74805-440",
      coordinate: {
        latitude: -16.7024392,
        longitude: -49.2386916,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '4',
      image: 'https://lh5.googleusercontent.com/p/AF1QipNzYL21o0kfS2z607gMMwnHVTWamBzzSdvw9_Ui=w408-h725-k-no',
      type: 'Apartamento Duplex',
      title: 'Typical canarian house',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      bed: 4,
      bedroom: 3,
      oldPrice: "1.850.000,00",
      newPrice: "1.430.000,00",
      totalPrice: "1.450.000,00",
      address: "R. 46, 555 - Jardim Goiás, Goiânia - GO",
      cep: "74805-440",
      coordinate: {
        latitude: -16.6989088,
        longitude: -49.2437911,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '5',
      image: 'https://lh5.googleusercontent.com/p/AF1QipNzYL21o0kfS2z607gMMwnHVTWamBzzSdvw9_Ui=w408-h725-k-no',
      type: 'Apartamento Duplex',
      title: 'Typical canarian house',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      bed: 4,
      bedroom: 3,
      oldPrice: "1.850.000,00",
      newPrice: "1.430.000,00",
      totalPrice: "1.450.000,00",
      address: "R. 46, 555 - Jardim Goiás, Goiânia - GO",
      cep: "74805-440",
      coordinate: {
        latitude: -16.6985867,
        longitude: -49.2438828,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '6',
      image: 'https://lh5.googleusercontent.com/p/AF1QipNzYL21o0kfS2z607gMMwnHVTWamBzzSdvw9_Ui=w408-h725-k-no',
      type: 'Apartamento Duplex',
      title: 'Typical canarian house',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      bed: 4,
      bedroom: 3,
      oldPrice: "1.850.000,00",
      newPrice: "1.430.000,00",
      totalPrice: "1.450.000,00",
      address: "R. 46, 555 - Jardim Goiás, Goiânia - GO",
      cep: "74805-440",
      coordinate: {
        latitude: -16.7029108,
        longitude: -49.2361277,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
    {
      id: '7',
      image: 'https://lh5.googleusercontent.com/p/AF1QipNzYL21o0kfS2z607gMMwnHVTWamBzzSdvw9_Ui=w408-h725-k-no',
      type: 'Apartamento Duplex',
      title: 'Typical canarian house',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      bed: 4,
      bedroom: 3,
      oldPrice: "1.850.000,00",
      newPrice: "1.430.000,00",
      totalPrice: "1.450.000,00",
      address: "R. 46, 555 - Jardim Goiás, Goiânia - GO",
      cep: "74805-440",
      coordinate: {
        latitude: -16.7032079,
        longitude: -49.239429,
        latitudeDelta: 0,
        longitudeDelta: 0
      },
    },
  ];